apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      initContainers:
        - name: migration
          image: imranstacklearner/product:813ebc5
          command: ["yarn", "migrate:dev"]
          env:
            - name: PRODUCT_DATABASE_URL
              value: "postgresql://postgres:root@postgres.default.svc.cluster.local:5432/product_db?schema=public"
      containers:
        - name: product
          image: imranstacklearner/product:813ebc5
          ports:
            - containerPort: 4001
          env:
            - name: PRODUCT_DATABASE_URL
              value: "postgresql://postgres:root@postgres.default.svc.cluster.local:5432/product_db?schema=public"
            - name: INVENTORY_SERVICE_URL
              value: "http://inventory-service.default.svc.cluster.local"
