apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: imranstacklearner/product:813ebc5
          ports:
            - containerPort: 4001
          env:
            - name: PRODUCT_DATABASE_URL
              value: "postgresql://postgres:root@postgres.default.svc.cluster.local:5432/product_db?schema=public"
            - name: INVENTORY_SERVICE_URL
              value: "http://inventory-service.default.svc.cluster.local:4002"
          #   - name: DATABASE_USER
          #     valueFrom:
          #       secretKeyRef:
          #         name: product-secrets
          #         key: database-user
          #   - name: DATABASE_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: product-secrets
          #         key: database-password
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"
