apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: imranstacklearner/product:latest
          ports:
            - containerPort: 5004
          env:
            - name: DATABASE_HOST
              value: "your_database_host"
            - name: DATABASE_PORT
              value: "your_database_port"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: product-secrets
                  key: database-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-secrets
                  key: database-password
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
