apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: imranstacklearner/cart:9fbff0f
          ports:
            - containerPort: 4004  # Adjust the container port as needed
          env:
            - name: REDIS_HOST
              value: "redis-stack.default.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: CART_TTL
              value: "120"  
            - name: INVENTORY_SERVICE_URL
              value: "http://inventory-service.default.svc.cluster.local"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@pmw-rabbit-mq.default.svc.cluster.local/"
              
            # Add more environment variables as needed
          # resources:
          #   requests:
          #     memory: "64Mi"  # Adjust memory request
          #     cpu: "250m"     # Adjust CPU request
          #   limits:
          #     memory: "128Mi" # Adjust memory limit
          #     cpu: "500m"     # Adjust CPU limit
