apiVersion: v1
kind: Secret
metadata:
  name: cart-service-secret
type: Opaque
data:
  database_username: base64_encoded_username
  database_password: base64_encoded_password
  api_key: base64_encoded_api_key
