apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      initContainers:
        - name: order-migrate
          image: imranstacklearner/order:462647f
          command: ["yarn" , "migrate:dev"]
          env:
            - name: ORDER_DATABASE_URL
              value: "postgresql://postgres:root@postgres.default.svc.cluster.local:5432/order_db?schema=public"
      containers:
        - name: order
          image: imranstacklearner/order:462647f
          ports:
            - containerPort: 4007
          env:
            - name: ORDER_DATABASE_URL
              value: "postgresql://postgres:root@postgres.default.svc.cluster.local:5432/order_db?schema=public"
            - name: CART_SERVICE_URL
              value: "http://cart-service.default.svc.cluster.local"
            - name: EMAIL_SERVICE_URL
              value: "http://email-service.default.svc.cluster.local"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service.default.svc.cluster.local"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@pmw-rabbit-mq.default.svc.cluster.local/"
