apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: imranstacklearner/order:latest
          ports:
            - containerPort: 5003
          env:
            - name: DATABASE_HOST
              value: "your_database_host"
            - name: DATABASE_PORT
              value: "your_database_port"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: order-secrets
                  key: database-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-secrets
                  key: database-password
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
