apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/keycloak" # Change this to the actual path on your host machine