apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/keycloak" # Change this to the actual path on your host machine

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8081
      targetPort: 8080
  type: NodePort

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
type: Opaque
data:
  DB_PASSWORD: cm9vdA==
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4= # base64 encoded "admin" as default admin password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: bitnami/keycloak:latest
          env:
            - name: DB_VENDOR
              value: POSTGRES
            - name: DB_ADDR
              value: postgres.default.svc.cluster.local
            - name: DB_DATABASE
              value: keycloak
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: DB_PASSWORD
            - name: KEYCLOAK_ADMIN_USER
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /bitnami/keycloak
              name: keycloak-data
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-pvc
