apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      # initContainers:
      #   - name: wait-for-db
      #     image: bitnami/keycloak:latest
      #     command: ["/bin/bash", "-c"]
      #     args:
      #       - |
      #         until pg_isready -h postgres.default.svc.cluster.local -U postgres; do sleep 2; done;
      containers:
        - name: keycloak
          image: bitnami/keycloak:latest
          env:
            - name: DB_VENDOR
              value: POSTGRES
            - name: DB_ADDR
              value: postgres.default.svc.cluster.local
            - name: DB_DATABASE
              value: keycloak
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: DB_PASSWORD
            - name: KEYCLOAK_ADMIN_USER
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /bitnami/keycloak
              name: keycloak-data
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-pvc
