apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
        - name: migration-init-container
          image: imranstacklearner/auth:b602a48  # Same image as the main container
          command: ["yarn", "migrate:dev"]  # Command to run yarn migration:dev
          envFrom:
            - configMapRef:
                name: auth-config  # Reference to the ConfigMap for environment variables
      containers:
        - name: auth
          image: imranstacklearner/auth:b602a48
          ports:
            - containerPort: 4003
          envFrom:
            - configMapRef:
                name: auth-config  # Reference to the ConfigMap for environment variables
          #   - secretRef:
          #       name: auth-secrets  # Reference to the Secret
          # resources:
          #   requests:
          #     memory: "64Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
