# pmw-k8s-configs/auth-service/auth-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  DATABASE_PASSWORD: "BASE64_ENCODED_PASSWORD"  # Use base64 encoded value
  # Add more key-value pairs as needed
