# pmw-k8s-configs/auth-service/auth-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  AUTH_DATABASE_URL: "postgresql://postgres:root@postgres.default.svc.cluster.local:5432/auth_db?schema=public"
  JWT_SECRET: "your_secret_key"
  EMAIL_SERVICE_URL: "http://email-service.default.svc.cluster.local"
  USER_SERVICE_URL : "http://user-service.default.svc.cluster.local"

