# pmw-k8s-configs/auth-service/auth-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  DATABASE_URL: "your_database_url"
  SECRET_KEY: "your_secret_key"
  JWT_SECRET: "your_jwt_secret"
  # Add more key-value pairs as needed
