# pmw-k8s-configs/auth-service/auth-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: imranstacklearner/auth:6391446
          ports:
            - containerPort: 5002
          envFrom:
            - configMapRef:
                name: auth-config  # Reference to the ConfigMap
            - secretRef:
                name: auth-secrets  # Reference to the Secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
