apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      initContainers:
        - name: migration
          image: imranstacklearner/user:ddd3aee
          command: ["yarn", "migrate:dev"]
          env:
            - name: USER_DATABASE_URL
              value: "postgresql://postgres:root@postgres.default.svc.cluster.local:5432/user_db?schema=public"
      containers:
        - name: user
          image: imranstacklearner/user:ddd3aee
          ports:
            - containerPort: 4000
          env:
            - name: USER_DATABASE_URL
              value: "postgresql://postgres:root@postgres.default.svc.cluster.local:5432/user_db?schema=public"
            # Add other database environment variables here if needed
