apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: imranstacklearner/user:ddd3aee
          ports:
            - containerPort: 4000
          env:
            - name: USER_DATABASE_URL
              value: "postgresql://postgres:root@postgres.default.svc.cluster.local:5432/user_db?schema=public"
            # - name: DATABASE_PORT
            #   value: "your_database_port"
            # - name: USER_DATABASE_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: user-database-url
            #       key: database-url
            # - name: DATABASE_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: user-secrets
            #       key: database-password
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"
