apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmw-rabbit-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pmw-rabbit-mq
  template:
    metadata:
      labels:
        app: pmw-rabbit-mq
    spec:
      containers:
        - name: pmw-rabbit-mq
          image: rabbitmq:3.8-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pv-claim

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv-volume
  labels:
    type: local
    app: pmw-rabbit-mq
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/rabbitmq-data" # Change this to the actual path on your host machine

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: pmw-rabbit-mq
  labels:
    app: pmw-rabbit-mq
spec:
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      nodePort: 30672
    - name: http
      port: 15672
      targetPort: 15672
      nodePort: 31672
  type: NodePort
  selector:
    app: pmw-rabbit-mq
