# .github/workflows/update-k8s-config-email.yaml
name: Update Kubernetes Config - Email Service

on:
  workflow_run:
    workflows: ["Build and Push Docker Image - Email Service"]
    types:
      - completed
  workflow_dispatch:

jobs:
  update-k8s-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git configuration
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Download and install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.11.2/yq_linux_amd64 -O $HOME/yq
          chmod +x $HOME/yq
          echo "$HOME" >> $GITHUB_PATH

      - name: Get commit hash from Docker image workflow
        id: get_commit_hash
        run: echo "::set-output name=hash::$(cat $GITHUB_EVENT_PATH | jq -r '.workflow_run.head_commit.id')"

      - name: Fetch Kubernetes configurations from pmw-k8s-configs repository
        run: |
          # Clone the repository containing Kubernetes configurations
          git clone https://github.com/Stack-Learner/pmw-k8s-configs.git
          cd pmw-k8s-configs/email-service

          # Bash script to update image tag in deployment file
          DEPLOYMENT_FILE="email-deployment.yaml"
          if [ -n "$GITHUB_SHA" ]; then
              $HOME/yq eval -i '.spec.containers[0].image |= "imranstacklearner/email:'"$GITHUB_SHA"'"' $DEPLOYMENT_FILE
              echo "Updated image tag in $DEPLOYMENT_FILE to: $GITHUB_SHA"
              git add $DEPLOYMENT_FILE
              git commit -m "Update image tag to $GITHUB_SHA"
              git push
          else
              echo "GITHUB_SHA environment variable not set. Exiting."
          fi
