# .github/workflows/update-k8s-config-email.yaml
name: Update Kubernetes Config - Email Service

on:
  workflow_run:
    workflows: ["Build and Push Docker Image - Email Service"]
    types:
      - completed
  workflow_dispatch:


jobs:
  update-k8s-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit hash from Docker image workflow
        id: get_commit_hash
        run: echo "::set-output name=hash::$(cat $GITHUB_EVENT_PATH | jq -r '.workflow_run.head_commit.id')"

      - name: Fetch Kubernetes configurations from pmw-k8s-configs repository
        run: |
          # Clone the repository containing Kubernetes configurations
          git clone https://github.com/Stack-Learner/pmw-k8s-configs.git
          cd pmw-k8s-configs/email-service

          # Update deployment file for the email service
          sed -i "s|imranstacklearner/email:{{ COMMIT_HASH }}|imranstacklearner/email:${{ steps.get_commit_hash.outputs.hash }}|" email-deployment.yaml

          # Stage the modified file for commit
          git add email-deployment.yaml
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git commit -m "Update image tag to ${{ steps.get_commit_hash.outputs.hash }}"
          git push
