apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
  type: NodePort
  nodePort: 30080  # You can choose a specific port within the allowed range
